### ISSUE TITLE
Settings Display Bug

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/HFX2.0#1]
Settings for different pages will not be visible until that page has been loaded.

To replicate:
- Load extension, then navigate to UserCP. Game settings will not be visible until you navigate to game.php

**Comment by xadamxk** [comment]
#34

**Comment by TyrantKingBen** [comment]
This is because of how things are defined in the extension manifest (`manifest.json`). It only loads those features when the appropriate pages are visited, so it doesn't initialize the settings until then.

**Comment by xadamxk** [comment]
> This is because of how things are defined in the extension manifest (`manifest.json`). It only loads those features when the appropriate pages are visited, so it doesn't initialize the settings until then.

I added everything to global as a temporary workaround until the settings bug was fixed. I will fix the duplications in global, by removing everything but global, and that should fix the issue.

**Comment by TyrantKingBen** [comment]
> > This is because of how things are defined in the extension manifest (`manifest.json`). It only loads those features when the appropriate pages are visited, so it doesn't initialize the settings until then.
> 
> I added everything to global as a temporary workaround until the settings bug was fixed. I will fix the duplications in global, by removing everything but global, and that should fix the issue.

It's not the section names that matter, but the rules in the extension manifest. I've almost finished some changes that would allow working around this.
