### ISSUE TITLE
Extend feature framework functionality to allow an option to disable the ability to disable a feature

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/HFX2.0#140]

**Comment by xadamxk** [comment]
Will be used in HFX Alerts and HFX Trophies.

**Comment by xHeaven** [comment]
Would be nice if we would have dependencies as well.
Let's say we have **2 modules**, we call them **module1** and **module2**.
**module1** is completely independent, however, **module2** depends on **module1**. So, if **module1** is disabled, you can't turn **module2** on, or if both are enabled, you can't turn off **module1** before **module2**.

I think this could be somehow an addition to this enhancement.

**Comment by xadamxk** [comment]
In that scenario, you would use the existing functionality of configurables.
Here is a basic example where the parent feature (ExpandProfileSections) has a child feature (Expand Awards), but if the parent feature is disabled, the child feature will not run.

All available configurables can be found here: https://github.com/xadamxk/HFX2.0/tree/develop/src/configurables
And examples can be found in the readme or modules throughout the project.

Is this what you meant as far as functionality goes?

**Comment by xHeaven** [comment]
Yes, this is it, I missed that potential with the configurables. Thanks!
