### ISSUE TITLE
Ignored users posts still showing

### ISSUE THREAD

**Issue by T0BiD** [xadamxk/HFX2.0#190]
Is there reason why the posts by an ignored user are still showing? And if yes, can I turn it off?

I ignored them for a reason, I don't want to see anything from them.

I'd even like a feature where I could hide everything from an ignored user so they don't even exists in my version of HF :D
But that's another topic and something I could probably implement myself.

**Comment by xadamxk** [comment]
Let's double check a few things before making a task out of this:
1. Go to Settings > Threads
Is 'Expand Blocked Posts' enabled? If so, disable it.
Is 'Hide Blocked Posts' enabled? If not, enable it.

Let me know, thanks!

**Comment by xadamxk** [comment]
Closing this issue due to lack of feedback.
