### ISSUE TITLE
Linked Awards Feature

### ISSUE THREAD

**Issue by lessevv** [xadamxk/HFX2.0#204]
PR includes the following:

- Small fix in contributing.md 
- Update Dockerfile and replace MAINTAINER with new LABEL tag
- Adds the Linked Awards feature

PR: https://github.com/xadamxk/HFX2.0/pull/205

**Comment by xadamxk** [comment]
Think you'll be able to finish this up in the next few days? 
If not, I may do it. @lessevv

**Comment by lessevv** [comment]
> Think you'll be able to finish this up in the next few days? If not, I may do it. @lessevv

I probably will be, yes. I'll keep you updated.

**Comment by xadamxk** [comment]
> > Think you'll be able to finish this up in the next few days? If not, I may do it. @lessevv
> 
> I probably will be, yes. I'll keep you updated.

Going to update it tomorrow if you can't.

**Comment by lessevv** [comment]
> > > Think you'll be able to finish this up in the next few days? If not, I may do it. @lessevv
> > 
> > 
> > I probably will be, yes. I'll keep you updated.
> 
> Going to update it tomorrow if you can't.

I actually have the work done, just need to properly test it. You can see it in my fork.

**Comment by xadamxk** [comment]
> I actually have the work done, just need to properly test it. You can see it in my fork.

Awesome! I'll test it if you make a PR for it.
