### ISSUE TITLE
Show carret next to expandable options

### ISSUE THREAD

**Issue by yani** [xadamxk/HFX2.0#270]
This is just an inspect element edit but it shows the idea:
![image](https://user-images.githubusercontent.com/6956790/209476271-196261c5-3683-4352-a234-52aa09bcd760.png)

It took a while before I realized I could expand the blue options.

**Comment by xadamxk** [comment]
Bootstrap's default behavior for this isn't great.
I wanted to redo the UI for settings, but this might be the solution that gets implemented.
