### ISSUE TITLE
Default notification sound url is dead

### ISSUE THREAD

**Issue by yani** [xadamxk/HFX2.0#271]
Default notification sound url is dead:
```
https://store2.gofile.io/download/ca848df4-fc96-4496-83e3-457b77fa062c/mixkit-message-pop-alert-2354.mp3
```

Maybe add a default sound in the extension itself?

Using a github link might be good enough too. But I personally think that should be avoided as much as possible.

**Comment by xadamxk** [comment]
Seems like you are using the extension from source and not what is deployed?
`develop` is working - master is missing the fix that develop has until I merge changes into it.

**Comment by xadamxk** [comment]
Will be handled in #275 thanks for bringing this up!
