### ISSUE TITLE
Convo Features

### ISSUE THREAD

**Issue by moodiest** [xadamxk/HFX2.0#83]
* [x] <del>**Whitelist Users**
  * Only messages sent by users in the whitelist will be seen.</del>
* [x] <del>**Blacklist Users**
  * Messages sent by users in the blacklist will be filtered out.</del>
* [ ] **Online Rings**
  * Display a green ring around profile pictures to indicate if a user is currently in the chat room or not.
* [x] <del>**Ignore Buttons**
  * Add and remove users from the blacklist when an ignore button is clicked on their modals</del>
* [ ] **Sidebar Organization**
  * Organize the sidebar with custom sorting styles. Include the ability to sort by secondary and tertiary user group, etc.
* [ ] **Emote System**
  * A fully fledged emote system for the convo room, similar to Twitch's BetterTwitchTV.
* [ ] **Quick Love Button**
  * Display a quick love button when hovering over messages, similar to Discord.
  * Randomly quick love one of the last x chatters. Support the whitelist and blacklist.
* [ ] <del>**Reactions**
  * Display reactions on messages and allow users to add reactions, similar to Discord.</del>
* [ ] **Convo Gambling Enhancements**
  * Improve the convo gambling experience. Potential to create specific sections to visualize the convo games.
* [ ] **Mention Highlights**
  * Highlight your username when you are mentioned.
  * Additional checkbox setting to play the audible chime when mentioned.
* [x] **Auto Full Screen**
  * Automatically enter full screen mode when visiting the convo page.
* [ ] <del>**Clear Message Box**
  * The message box should be cleared once the send or enter button is pressed, to prevent the possibility of sending a message twice.</del>
* [x] <del>**Voice Messages**
  * Record voice messages and send them in the convo room. Parse the voice message and play them. Would likely feature a function to record audio that is uploaded to a webserver and then embedded when linked.</del>
* [ ] **Custom Theme**
  * Custom Discord-like theme for convos.
* [ ] **Message Timestamps**
  * Show relative timestamps under each message (relative if less than a day, absolute if greater)

**Comment by xadamxk** [comment]
Can you specify `Clear Message Box`, because when I hit enter or the send button, the textbox is cleared.

**Comment by xadamxk** [comment]
The implementation of `Reactions` would require a backend, which I don't think belongs in HFX.

**Comment by xadamxk** [comment]
`Sidebar Organization` would only be feasible if that additional usergroup information is available without an additional page request, otherwise it will be unrealistic.

**Comment by xadamxk** [comment]
Is there an existing function in chat for quick love? If not, I am not sure `Random Quick Loves` will be feasible because it will require you to load the user's posts, pick one, and quick love them, which will be too many requests.

**Comment by xadamxk** [comment]
And lastly, `Custom Theme` is possible, but it will be unrealistic to make all convo features compatible with it, because we would have to have different logic based on the theme. So initially if users choose to use this custom theme, they might miss out on extra features for the time being.

**Comment by xadamxk** [comment]
Just an idea for `Mention Highlights`, maybe an additional checkbox to play the default chime ONLY when you get mentioned?

**Comment by xadamxk** [comment]
`Whitelist Users`, `Blacklist Users`, and `Ignore Buttons` are already implemented on my working branch, which is still a work in progress: https://github.com/xadamxk/HFX2.0/tree/feature/implement-convo-module

I've updated your initial issue based off suggestions and feedback. Would you mind canceling this issue and making individual issues for the remaining features?
