### ISSUE TITLE
Convo Emote System

### ISSUE THREAD

**Issue by moodiest** [xadamxk/HFX2.0#97]
A fully fledged emote system for the convo room, similar to Twitch's BetterTwitchTV.

**Comment by xadamxk** [comment]
Are you thinking like an emote picker using standard emotes?
Or full on custom emotes?

**Comment by moodiest** [comment]
> Are you thinking like an emote picker using standard emotes?
> Or full on custom emotes?

Custom emotes. Things like pepe the frog, twitch emotes, etc.
